[workspace]
members = [
    "crates/photo-culler-core",
    "crates/photo-culler-image-engine",
    "apps/photo-culler-cli",
    "apps/photo-culler-egui",
    "apps/photo-culler-tauri",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "tiff"] }
photo-culler-core = { path = "crates/photo-culler-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rustfft = "6"
